(function(){
"use strict";

var ACCESS_PASSWORD="78789852";
var SYSTEM_KEY="78789852";
var DB_NAME="sales_webapp_flat_accounts_v1";
var DB_VERSION=1;
var STORES=["settings","accounts","customers","products","invoices","debts","payments","dailySales","purchases","transactions","syncQueue","syncLogs"];
var db=null, syncing=false, fbReady=false, fbListening=false, deferredInstallPrompt=null;

var firebaseConfig={apiKey:"AIzaSyCKanr7CGbYN976gNtQNaEd8wOfM3foqTE",authDomain:"jooo-fade0.firebaseapp.com",projectId:"jooo-fade0",storageBucket:"jooo-fade0.firebasestorage.app",messagingSenderId:"390273445209",appId:"1:390273445209:web:995e7b0f45c64c5c2d3048",measurementId:"G-HCYE383B5T",databaseURL:"https://jooo-fade0-default-rtdb.firebaseio.com"};

var state={route:"dashboard",selectedCustomerId:null,settings:null,accounts:[],customers:[],products:[],invoices:[],debts:[],payments:[],dailySales:[],purchases:[],transactions:[],syncQueue:[],syncLogs:[],lastInvoice:null};

var icons={
store:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M4 10h16l-1-6H5l-1 6Z"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/><path d="M4 10a3 3 0 0 0 6 0 3 3 0 0 0 6 0 3 3 0 0 0 6 0"/></svg>',
home:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M3 11.5 12 4l9 7.5"/><path d="M5 10.5V20h14v-9.5"/><path d="M9 20v-6h6v6"/></svg>',
receipt:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M7 3h10a2 2 0 0 1 2 2v16l-3-2-2 2-2-2-2 2-2-2-3 2V5a2 2 0 0 1 2-2Z"/><path d="M9 8h6M9 12h6M9 16h4"/></svg>',
payment:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18"/><path d="M7 15h4"/></svg>',
chart:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M4 19V5"/><path d="M4 19h16"/><rect x="7" y="11" width="3" height="5" rx="1"/><rect x="12" y="7" width="3" height="9" rx="1"/><rect x="17" y="13" width="3" height="3" rx="1"/></svg>',
debt:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M7 4h10a2 2 0 0 1 2 2v14l-7-3-7 3V6a2 2 0 0 1 2-2Z"/><path d="M9 9h6M9 13h4"/></svg>',
box:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="m3 7 9-4 9 4-9 4-9-4Z"/><path d="M3 7v10l9 4 9-4V7"/><path d="M12 11v10"/></svg>',
truck:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M3 6h12v10H3z"/><path d="M15 10h4l2 3v3h-6z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></svg>',
settings:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M12 15.5A3.5 3.5 0 1 0 12 8a3.5 3.5 0 0 0 0 7.5Z"/><path d="M19.4 15a1.8 1.8 0 0 0 .36 1.98l.04.04a2 2 0 0 1-2.83 2.83l-.04-.04A1.8 1.8 0 0 0 15 19.4a1.8 1.8 0 0 0-1 .6 1.8 1.8 0 0 0-.5 1.3V21a2 2 0 0 1-4 0v-.06A1.8 1.8 0 0 0 8.5 19.4a1.8 1.8 0 0 0-1.98.36l-.04.04a2 2 0 0 1-2.83-2.83l.04-.04A1.8 1.8 0 0 0 4.6 15a1.8 1.8 0 0 0-.6-1 1.8 1.8 0 0 0-1.3-.5H3a2 2 0 0 1 0-4h.06A1.8 1.8 0 0 0 4.6 8.5a1.8 1.8 0 0 0-.36-1.98l-.04-.04a2 2 0 0 1 2.83-2.83l.04.04A1.8 1.8 0 0 0 9 4.6a1.8 1.8 0 0 0 1-.6 1.8 1.8 0 0 0 .5-1.3V3a2 2 0 0 1 4 0v.06a1.8 1.8 0 0 0 1 1.54 1.8 1.8 0 0 0 1.98-.36l.04-.04a2 2 0 0 1 2.83 2.83l-.04.04A1.8 1.8 0 0 0 19.4 9c.3.3.6.6 1 .6h.6a2 2 0 0 1 0 4h-.06a1.8 1.8 0 0 0-1.54 1Z"/></svg>',
wallet:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M4 7h15a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h12"/><path d="M16 13h5"/><circle cx="17.5" cy="13" r="1"/></svg>',
users:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M16 21v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2"/><circle cx="9.5" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
alert:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M10.3 4.3 2.5 18a2 2 0 0 0 1.7 3h15.6a2 2 0 0 0 1.7-3L13.7 4.3a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg>',
menu:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M4 6h16M4 12h16M4 18h16"/></svg>',
moon:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M21 12.8A8.5 8.5 0 1 1 11.2 3a6.5 6.5 0 0 0 9.8 9.8Z"/></svg>',
sync:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M21 12a9 9 0 0 1-15.5 6.2L3 16"/><path d="M3 16h6v-6"/><path d="M3 12A9 9 0 0 1 18.5 5.8L21 8"/><path d="M21 8h-6v6"/></svg>',
account:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="M7 9h10"/><path d="M7 13h6"/><path d="M16 16h1"/></svg>',
clock:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>',
cloud:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M17.5 19H7a5 5 0 1 1 1-9.9A7 7 0 0 1 21 12.5 3.5 3.5 0 0 1 17.5 19Z"/></svg>'
};
function icon(n){return '<span class="icon">'+(icons[n]||icons.store)+'</span>'}

var routes=[
{id:"dashboard",title:"الرئيسية",subtitle:"ملخص الحسابات والمبيعات",icon:"home"},
{id:"invoices",title:"الفواتير",subtitle:"بيع مع مبلغ مدفوع ومتبقي كدين",icon:"receipt"},
{id:"customers",title:"العملاء",subtitle:"إضافة العملاء وملفاتهم",icon:"users"},
{id:"debts",title:"الديون",subtitle:"ديون العملاء والسداد",icon:"debt"},
{id:"accounts",title:"الحسابات",subtitle:"حسابات الصندوق والبنك والجهات",icon:"account"},
{id:"payments",title:"الدفعات",subtitle:"سداد ديون العملاء إلى حساب محدد",icon:"payment"},
{id:"sales",title:"المبيعات",subtitle:"سجل المبيعات",icon:"chart"},
{id:"products",title:"المنتجات",subtitle:"المخزون والباركود",icon:"box"},
{id:"purchases",title:"المشتريات",subtitle:"واردات وصادرات الحسابات",icon:"truck"},
{id:"settings",title:"الإعدادات",subtitle:"النظام والمزامنة والتثبيت",icon:"settings"}
];
var bottomIds=["dashboard","invoices","debts","accounts","payments","products"];

document.addEventListener("DOMContentLoaded",boot);

function $(id){return document.getElementById(id)}
function val(id){var e=$(id);return e?e.value:""}
function setVal(id,v){var e=$(id);if(e)e.value=v}
function html(id,v){var e=$(id);if(e)e.innerHTML=v}
function text(id,v){var e=$(id);if(e)e.textContent=v}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(m){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]})}
function toNumber(v){var n=Number(v);return Number.isFinite(n)?n:0}
function fmt(n){return Number(n||0).toLocaleString("en-US",{maximumFractionDigits:2})}
function money(v){return fmt(toNumber(v))+" "+((state.settings&&state.settings.currency)||"شيكل")}
function uid(p){return p+"_"+Date.now()+"_"+Math.random().toString(16).slice(2)}
function nowBase(o){o=o||{};o.createdAt=o.createdAt||Date.now();o.updatedAt=Date.now();o.syncStatus="pending";o.isDeleted=false;return o}
function active(a){return (a||[]).filter(function(x){return !x.isDeleted})}
function today(){var d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function statusText(s){return {cash:"كاش",bank:"بنك",transfer:"تحويل",deferred:"آجل",paid:"مدفوع",partial:"جزئي",unpaid:"غير مدفوع",overdue:"متأخر",income:"وارد",expense:"صادر"}[s]||s||"-"}
function statusClass(s){return ["paid","income","cash"].includes(s)?"success":["partial","bank","transfer"].includes(s)?"warning":["unpaid","overdue","expense","deferred"].includes(s)?"danger":""}
function chip(s){return '<span class="chip '+statusClass(s)+'">'+statusText(s)+'</span>'}
function toast(m,t){var e=document.createElement("div");e.className="toast "+(t||"");e.textContent=m;$("toastHost").appendChild(e);setTimeout(function(){e.remove()},3500)}

function boot(){
 $("loginLogo").innerHTML=icon("store");$("menuBtn").innerHTML=icon("menu");$("themeBtn").innerHTML=icon("moon");$("syncIcon").innerHTML='<span class="sync-spin">'+icon("sync")+'</span>';
 document.body.classList.toggle("dark",localStorage.getItem("sales_theme")==="dark");
 buildNav();
 openDB().then(ensureDefaults).then(loadAll).then(function(){applyBrand();bindShell();watchConnection();initPWA();initLogin();if(localStorage.getItem("sales_access_ok")==="1"){showApp();navigate(localStorage.getItem("sales_last_route")||"dashboard");syncNow(true);startRealtime()}});
 if("serviceWorker" in navigator){navigator.serviceWorker.register("./service-worker.js").catch(function(){})}
}
function openDB(){return new Promise(function(res,rej){var r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=function(e){var d=e.target.result;STORES.forEach(function(n){if(!d.objectStoreNames.contains(n)){var s=d.createObjectStore(n,{keyPath:"id"});s.createIndex("updatedAt","updatedAt",{unique:false});s.createIndex("syncStatus","syncStatus",{unique:false})}})};r.onsuccess=function(){db=r.result;res()};r.onerror=function(){rej(r.error)}})}
function store(n,m){return db.transaction(n,m||"readonly").objectStore(n)}
function getAll(n){return new Promise(function(res,rej){var r=store(n).getAll();r.onsuccess=function(){res(r.result||[])};r.onerror=function(){rej(r.error)}})}
function getOne(n,id){return new Promise(function(res,rej){var r=store(n).get(id);r.onsuccess=function(){res(r.result)};r.onerror=function(){rej(r.error)}})}
function putOne(n,v){return new Promise(function(res,rej){var r=store(n,"readwrite").put(v);r.onsuccess=function(){res(v)};r.onerror=function(){rej(r.error)}})}
function delOne(n,id){return new Promise(function(res,rej){var r=store(n,"readwrite").delete(id);r.onsuccess=function(){res(true)};r.onerror=function(){rej(r.error)}})}
function clearStore(n){return getAll(n).then(function(a){return Promise.all(a.map(function(x){return delOne(n,x.id)}))})}
function loadAll(){return Promise.all(STORES.map(function(n){return getAll(n).then(function(a){state[n]=a})})).then(function(){state.settings=(state.settings||[]).find(function(x){return x.id==="main"})||null})}
function ensureDefaults(){
 return getOne("settings","main").then(function(s){
  var tasks=[];
  if(!s){s=nowBase({id:"main",storeName:"نظام إدارة المبيعات",logoUrl:"",openingBalance:0,currency:"شيكل",password:ACCESS_PASSWORD});tasks.push(putOne("settings",s).then(function(){return queueSync("settings","main","update",s)}))}
  return getAll("accounts").then(function(accs){
    if(!active(accs).length){
      var cash=nowBase({id:uid("account"),entityName:"الصندوق",accountName:"نقدي",openingBalance:0,type:"cash"});
      var bank=nowBase({id:uid("account"),entityName:"البنك",accountName:"حساب بنكي",openingBalance:0,type:"bank"});
      tasks.push(putOne("accounts",cash).then(function(){return queueSync("accounts",cash.id,"create",cash)}));
      tasks.push(putOne("accounts",bank).then(function(){return queueSync("accounts",bank.id,"create",bank)}));
    }
    return Promise.all(tasks);
  });
 });
}
function initLogin(){
 $("loginForm").onsubmit=function(e){e.preventDefault();var pass=val("loginPassword").trim(),saved=(state.settings&&state.settings.password)||ACCESS_PASSWORD;if(pass===saved){localStorage.setItem("sales_access_ok","1");$("loginPassword").value="";showApp();navigate("dashboard");syncNow(true);startRealtime()}else{$("loginPassword").value="";toast("كلمة المرور غير صحيحة","danger")}};
}
function showApp(){$("loginScreen").classList.add("hidden");$("appShell").classList.remove("hidden")}
function buildNav(){html("sideNav",routes.map(function(r){return '<button class="nav-btn" data-nav="'+r.id+'">'+icon(r.icon)+'<span>'+r.title+'</span></button>'}).join(""));html("bottomNav",routes.filter(function(r){return bottomIds.includes(r.id)}).map(function(r){return '<button class="nav-btn" data-nav="'+r.id+'">'+icon(r.icon)+'<span>'+r.title+'</span></button>'}).join(""))}
function bindShell(){
 document.body.addEventListener("click",function(e){var b=e.target.closest("[data-nav]");if(b){navigate(b.dataset.nav);closeSide()}});
 $("menuBtn").onclick=function(){$("sidebar").classList.add("open");$("sidebarBackdrop").classList.add("open")};
 $("sidebarBackdrop").onclick=closeSide;
 $("themeBtn").onclick=function(){document.body.classList.toggle("dark");localStorage.setItem("sales_theme",document.body.classList.contains("dark")?"dark":"light")};
 $("logoutBtn").onclick=function(){localStorage.removeItem("sales_access_ok");location.reload()};
 $("syncBtn").onclick=function(){syncNow(false)};
}
function closeSide(){$("sidebar").classList.remove("open");$("sidebarBackdrop").classList.remove("open")}
function applyBrand(){var s=state.settings||{};text("brandName",s.storeName||"نظام إدارة المبيعات");var logo=s.logoUrl?'<img src="'+esc(s.logoUrl)+'" onerror="this.parentNode.innerHTML=\''+icon("store").replace(/'/g,"&#39;")+'\'">':icon("store");html("brandLogo",logo);html("loginLogo",logo)}
function setMeta(r){text("pageTitle",r.title);text("pageSubtitle",r.subtitle);document.querySelectorAll("[data-nav]").forEach(function(b){b.classList.toggle("active",b.dataset.nav===r.id)})}
function navigate(id){var r=routes.find(function(x){return x.id===id})||routes[0];state.route=r.id;localStorage.setItem("sales_last_route",r.id);setMeta(r);html("pageHost",templates[r.id]());setDates();bindPage();renderCurrent();enhanceSearchSelects()}
function setDates(){["invDate","paymentDate","debtDate","purchaseDate","txnDate","salesDateFilter"].forEach(function(id){var e=$(id);if(e&&!e.value)e.value=today()});var due=$("debtDueDate");if(due&&!due.value){var d=new Date();d.setDate(d.getDate()+7);setVal("debtDueDate",d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0"))}}
function bindPage(){
 if(state.route==="invoices"){bindCustomerSuggest("invCustomerName","invCustomerSuggest","invPhone","invCustomerDebtInfo");addInvoiceItemRow();$("addInvoiceItemBtn").onclick=addInvoiceItemRow;$("scanInvoiceBarcodeBtn").onclick=scanInvoiceProduct;$("saveInvoiceBtn").onclick=saveInvoice;$("clearInvoiceBtn").onclick=clearInvoiceForm;$("printInvoiceBtn").onclick=printLastInvoice;$("invoiceSearch").oninput=renderInvoices}
 if(state.route==="customers"){$("customerSearch").oninput=renderCustomers;$("saveCustomerBtn").onclick=saveCustomer;$("clearCustomerBtn").onclick=clearCustomerForm}
 if(state.route==="debts"){$("saveManualDebtBtn").onclick=saveManualDebt;$("debtSearch").oninput=renderDebtsPage;$("saveDebtPaymentBtn").onclick=savePayment}
 if(state.route==="accounts"){$("saveAccountBtn").onclick=saveAccount;$("clearAccountBtn").onclick=clearAccountForm;$("accountSearch").oninput=renderAccounts;$("saveTxnBtn").onclick=saveTransaction}
 if(state.route==="payments"){bindCustomerSuggest("paymentCustomerName","paymentCustomerSuggest","paymentPhone","paymentCustomerDebtInfo");$("savePaymentBtn").onclick=savePayment;$("paymentCustomerName").addEventListener("input",renderPaymentDebtOptions)}
 if(state.route==="sales"){$("salesDateFilter").onchange=renderSales;$("salesSearch").oninput=renderSales}
 if(state.route==="products"){$("saveProductBtn").onclick=saveProduct;$("clearProductBtn").onclick=clearProductForm;$("scanProductBarcodeBtn").onclick=function(){scanBarcode().then(function(c){if(c)setVal("productBarcode",c)})};$("productSearch").oninput=renderProducts}
 if(state.route==="purchases"){$("savePurchaseBtn").onclick=savePurchase}
 if(state.route==="settings"){hydrateSettings();$("saveSettingsBtn").onclick=saveSettings;$("exportDataBtn").onclick=exportAllJSON;$("clearDataBtn").onclick=clearAllData;$("settingsSyncBtn").onclick=function(){syncNow(false)};$("pullBtn").onclick=function(){pullFirebase().then(loadAll).then(renderCurrent).then(function(){toast("تم سحب البيانات","success")})};$("settingLogoUrl").oninput=function(){var i=$("settingsLogoPreview");if(i)i.src=val("settingLogoUrl")}}
}
function renderCurrent(){applyBrand();if(state.route==="dashboard")renderDashboard();if(state.route==="invoices"){renderAccountOptions();renderInvoices();calcInvoiceTotal()}if(state.route==="customers"){renderCustomers();renderAccountOptions()}if(state.route==="debts"){renderManualDebtArea();renderAccountOptions();renderPaymentDebtOptions();renderDebtsPage()}if(state.route==="accounts"){renderAccounts();renderAccountOptions();renderTransactions()}if(state.route==="payments"){renderAccountOptions();renderPaymentDebtOptions();renderPayments()}if(state.route==="sales")renderSales();if(state.route==="products")renderProducts();if(state.route==="purchases"){renderPurchaseProductOptions();renderAccountOptions();renderPurchases()}if(state.route==="settings"){hydrateSettings(false);renderSyncStatus()}enhanceSearchSelects()}

function table(headers,rows,id){id=id||"reportTable";if(!rows.length)return '<div class="empty">لا توجد بيانات.</div>';var htmlTable='<div id="'+id+'" class="table-wrap desktop-table"><table><thead><tr>'+headers.map(function(h){return '<th>'+h+'</th>'}).join("")+'</tr></thead><tbody>'+rows.map(function(r){return '<tr>'+r.map(function(c){return '<td>'+c+'</td>'}).join("")+'</tr>'}).join("")+'</tbody></table></div>';var mob='<div class="mobile-card-list">'+rows.map(function(r){return '<div class="record-card">'+r.map(function(c,i){return '<div class="record-line"><b>'+headers[i]+'</b><span>'+c+'</span></div>'}).join("")+'</div>'}).join("")+'</div>';return htmlTable+mob}
function tools(target,title){return '<div class="table-tools"><button class="btn small ghost" data-print="'+target+'">طباعة</button><button class="btn small ghost" data-pdf="'+target+'">PDF</button><button class="btn small ghost" data-img="'+target+'">صورة</button><button class="btn small ghost" data-csv="'+target+'">جدول CSV</button></div>'}
document.body.addEventListener("click",function(e){var p=e.target.closest("[data-print]"),pdf=e.target.closest("[data-pdf]"),img=e.target.closest("[data-img]"),csv=e.target.closest("[data-csv]");if(p)printElement(p.dataset.print);if(pdf)downloadPDF(pdf.dataset.pdf);if(img)downloadImage(img.dataset.img);if(csv)downloadCSV(csv.dataset.csv)});
function printElement(id){var el=$(id);if(!el){window.print();return}var w=window.open("","_blank");w.document.write('<html dir="rtl"><head><title>طباعة</title><style>body{font-family:Arial;padding:20px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ddd;padding:8px;text-align:right}th{background:#f3f4f6}</style></head><body>'+el.innerHTML+'</body></html>');w.document.close();w.print()}
function downloadImage(id){var el=$(id);if(!el){toast("لا يوجد جدول","warning");return}if(!window.html2canvas){toast("مكتبة الصورة تحتاج إنترنت","warning");return}html2canvas(el,{backgroundColor:"#ffffff"}).then(function(canvas){var a=document.createElement("a");a.href=canvas.toDataURL("image/png");a.download="report.png";a.click()})}
function downloadPDF(id){var el=$(id);if(!el){toast("لا يوجد جدول","warning");return}if(!window.html2canvas||!window.jspdf){toast("مكتبة PDF تحتاج إنترنت","warning");return}html2canvas(el,{backgroundColor:"#ffffff",scale:2}).then(function(canvas){var img=canvas.toDataURL("image/png");var pdf=new jspdf.jsPDF("p","mm","a4");var w=190,h=canvas.height*w/canvas.width;pdf.addImage(img,"PNG",10,10,w,h);pdf.save("report.pdf")})}
function downloadCSV(id){var el=$(id);if(!el){toast("لا يوجد جدول","warning");return}var rows=[].slice.call(el.querySelectorAll("tr")).map(function(tr){return [].slice.call(tr.children).map(function(td){return '"'+td.innerText.replace(/"/g,'""')+'"'}).join(",")}).join("\n");var blob=new Blob(["\ufeff"+rows],{type:"text/csv;charset=utf-8"});var a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="report.csv";a.click();URL.revokeObjectURL(a.href)}

function accountBalance(id){var acc=active(state.accounts).find(function(a){return a.id===id});var bal=toNumber(acc&&acc.openingBalance);active(state.transactions).filter(function(t){return t.accountId===id}).forEach(function(t){bal += t.type==="income"?toNumber(t.amount):-toNumber(t.amount)});return bal}
function totalAccounts(){return active(state.accounts).reduce(function(s,a){return s+accountBalance(a.id)},0)}
function openDebtTotal(){return active(state.debts).reduce(function(s,d){return s+toNumber(d.remaining)},0)}
function dashboardData(){var todaySales=active(state.dailySales).filter(function(s){return s.date===today()}).reduce(function(s,x){return s+toNumber(x.amount)},0);var low=active(state.products).filter(function(p){return toNumber(p.quantity)<=toNumber(p.minQuantity||0)});return {balance:totalAccounts(),todaySales:todaySales,debt:openDebtTotal(),low:low,customers:active(state.customers).length,invoices:active(state.invoices).length,accounts:active(state.accounts).length}}
function renderDashboard(){var d=dashboardData();text("currentBalance",money(d.balance));text("mTodaySales",money(d.todaySales));text("mInvoices",d.invoices);text("mDebts",money(d.debt));text("mAccounts",d.accounts);text("mCustomers",d.customers);text("mLowProducts",d.low.length);var rec=active(state.transactions).sort(function(a,b){return b.createdAt-a.createdAt}).slice(0,8);html("recentTransactions",rec.length?tools("txnMiniTable","آخر الحركات")+table(["التاريخ","الحساب","النوع","المبلغ","البيان"],rec.map(function(t){return [t.date||"-",esc(accountName(t.accountId)),chip(t.type),'<span class="money">'+money(t.amount)+'</span>',esc(t.note||"-")]}),"txnMiniTable"):'<div class="empty">لا توجد حركات.</div>')}

function customerDebtTotal(id){return active(state.debts).filter(function(d){return d.customerId===id}).reduce(function(s,d){return s+toNumber(d.remaining)},0)}
function setCustomerDebtInfo(targetId, customer){var el=$(targetId);if(!el)return;if(!customer){el.innerHTML='';return}el.innerHTML='<span class="chip '+(customerDebtTotal(customer.id)>0?'danger':'success')+'">دين العميل الحالي: '+money(customerDebtTotal(customer.id))+'</span>'}
function bindCustomerSuggest(inputId,boxId,phoneId,infoId){var inp=$(inputId),box=$(boxId);if(!inp||!box)return;inp.oninput=function(){var q=inp.value.trim().toLowerCase();if(infoId)setCustomerDebtInfo(infoId,null);if(q.length<2){box.classList.remove("open");box.innerHTML="";return}var list=active(state.customers).filter(function(c){return (c.name+" "+(c.phone||"")).toLowerCase().includes(q)}).slice(0,10);box.innerHTML=list.map(function(c){return '<button type="button" data-customer-pick="'+c.id+'"><b>'+esc(c.name)+'</b><small>'+esc(c.phone||'-')+' — عليه '+money(customerDebtTotal(c.id))+'</small></button>'}).join("");box.classList.toggle("open",!!list.length)};box.onclick=function(e){var b=e.target.closest("[data-customer-pick]");if(!b)return;var c=active(state.customers).find(function(x){return x.id===b.dataset.customerPick});if(c){inp.value=c.name;if(phoneId)setVal(phoneId,c.phone||"");if(infoId)setCustomerDebtInfo(infoId,c);box.classList.remove("open");renderPaymentDebtOptions()}}}
function upsertCustomer(name,phone){var f=active(state.customers).find(function(c){return (phone&&c.phone===phone)||c.name===name});if(f)return Promise.resolve(f);var c=nowBase({id:uid("customer"),name:name,phone:phone});return putOne("customers",c).then(function(){return queueSync("customers",c.id,"create",c)}).then(function(){state.customers.push(c);return c})}

function renderAccountOptions(){var opts=active(state.accounts).map(function(a){return '<option value="'+a.id+'">'+esc(a.entityName)+' - '+esc(a.accountName)+' - '+money(accountBalance(a.id))+'</option>'}).join("");["invPaidAccount","paymentAccount","purchaseAccount","txnAccount"].forEach(function(id){var s=$(id);if(s){var old=s.value;s.innerHTML=opts||'<option value="">أضف حسابًا أولًا</option>';if(old)s.value=old}})}
function accountName(id){var a=active(state.accounts).find(function(x){return x.id===id});return a?(a.entityName+" - "+a.accountName):"-"}
function saveAccount(){var id=val("accountEditId"),entity=val("accountEntity").trim(),name=val("accountName").trim(),opening=toNumber(val("accountOpening")),type=val("accountType");if(!entity||!name){toast("أكمل بيانات الحساب","warning");return}(id?getOne("accounts",id):Promise.resolve(null)).then(function(old){var a=nowBase(Object.assign({},old||{},{id:id||uid("account"),entityName:entity,accountName:name,openingBalance:opening,type:type,createdAt:(old&&old.createdAt)||Date.now()}));return putOne("accounts",a).then(function(){return queueSync("accounts",a.id,id?"update":"create",a)})}).then(loadAll).then(function(){clearAccountForm();renderCurrent();toast("تم حفظ الحساب","success")})}
function clearAccountForm(){["accountEditId","accountEntity","accountName","accountOpening"].forEach(function(id){setVal(id,"")});setVal("accountType","cash")}
function editAccount(id){var a=active(state.accounts).find(function(x){return x.id===id});if(!a)return;setVal("accountEditId",a.id);setVal("accountEntity",a.entityName||"");setVal("accountName",a.accountName||"");setVal("accountOpening",a.openingBalance||0);setVal("accountType",a.type||"cash")}
function renderAccounts(){var q=(val("accountSearch")||"").trim().toLowerCase();var arr=active(state.accounts).filter(function(a){return !q||(a.entityName+" "+a.accountName).toLowerCase().includes(q)}).sort(function(a,b){return b.createdAt-a.createdAt});html("accountsList",(arr.length?tools("accountsTable","الحسابات")+table(["الجهة","الحساب","رصيد افتتاحي","الرصيد الحالي","النوع","إجراءات"],arr.map(function(a){return [esc(a.entityName),esc(a.accountName),'<span class="money">'+money(a.openingBalance)+'</span>','<span class="money">'+money(accountBalance(a.id))+'</span>',esc(a.type||"-"),'<div class="actions"><button class="btn small ghost" data-edit-account="'+a.id+'">تعديل</button><button class="btn small danger" data-delete="accounts:'+a.id+'">حذف</button></div>']}),"accountsTable"):'<div class="empty">لا توجد حسابات.</div>'));document.querySelectorAll("[data-edit-account]").forEach(function(b){b.onclick=function(){editAccount(b.dataset.editAccount)}});bindDelete()}
function saveTransaction(){var accountId=val("txnAccount"),type=val("txnType"),amount=toNumber(val("txnAmount")),date=val("txnDate")||today(),note=val("txnNote").trim();if(!accountId||amount<=0){toast("اختر الحساب واكتب المبلغ","warning");return}var t=nowBase({id:uid("txn"),accountId:accountId,type:type,amount:amount,date:date,note:note,source:"manual"});putOne("transactions",t).then(function(){return queueSync("transactions",t.id,"create",t)}).then(loadAll).then(function(){setVal("txnAmount","");setVal("txnNote","");renderCurrent();toast("تم حفظ الحركة","success")})}
function renderTransactions(){var arr=active(state.transactions).sort(function(a,b){return b.createdAt-a.createdAt});html("transactionsList",arr.length?tools("transactionsTable","سجل الحسابات")+table(["التاريخ","الحساب","النوع","المبلغ","البيان","إجراءات"],arr.map(function(t){return [t.date||"-",esc(accountName(t.accountId)),chip(t.type),'<span class="money">'+money(t.amount)+'</span>',esc(t.note||"-"),'<button class="btn small danger" data-delete="transactions:'+t.id+'">حذف</button>']}),"transactionsTable"):'<div class="empty">لا توجد حركات حسابات.</div>');bindDelete()}

function productOptions(){return '<option value="">صنف يدوي</option>'+active(state.products).map(function(p){return '<option value="'+p.id+'" data-price="'+esc(p.price)+'">'+esc(p.name)+' - '+money(p.price)+' - كمية '+esc(p.quantity||0)+'</option>'}).join("")}
function addInvoiceItemRow(prefill){prefill=prefill||{};var w=$("invoiceItems");if(!w)return;var row=document.createElement("div");row.className="item-row";row.innerHTML='<label class="wide">الصنف<select class="invoice-product" data-search="1">'+productOptions()+'</select><input class="invoice-custom-name" placeholder="اسم الصنف اليدوي" value="'+esc(prefill.name||"")+'"></label><label>العدد<input class="invoice-qty" type="number" min="0" step="0.01" value="'+esc(prefill.quantity||1)+'"></label><label>السعر<input class="invoice-price" type="number" min="0" step="0.01" value="'+esc(prefill.price||0)+'"></label><label>المبلغ<input class="invoice-line-total" disabled value="0"></label><button class="btn danger small remove-item" type="button">حذف</button>';w.appendChild(row);var sel=row.querySelector(".invoice-product");if(prefill.productId)sel.value=prefill.productId;sel.onchange=function(){var p=active(state.products).find(function(x){return x.id===sel.value});if(p){row.querySelector(".invoice-custom-name").value=p.name;row.querySelector(".invoice-price").value=p.price||0}calcInvoiceTotal()};row.querySelectorAll(".invoice-qty,.invoice-price").forEach(function(e){e.oninput=calcInvoiceTotal});row.querySelector(".remove-item").onclick=function(){row.remove();calcInvoiceTotal()};sel.onchange();calcInvoiceTotal()}
function calcInvoiceTotal(){var total=0;document.querySelectorAll("#invoiceItems .item-row").forEach(function(row){var q=toNumber(row.querySelector(".invoice-qty").value),p=toNumber(row.querySelector(".invoice-price").value),line=q*p;row.querySelector(".invoice-line-total").value=fmt(line);total+=line});text("invoiceTotal",money(total));var paid=toNumber(val("invPaidAmount"));text("invoiceRemaining",money(Math.max(0,total-paid)));return total}
function getInvoiceItems(){return [].slice.call(document.querySelectorAll("#invoiceItems .item-row")).map(function(row){var pid=row.querySelector(".invoice-product").value,p=active(state.products).find(function(x){return x.id===pid}),name=row.querySelector(".invoice-custom-name").value.trim()||(p&&p.name)||"صنف",q=toNumber(row.querySelector(".invoice-qty").value),pr=toNumber(row.querySelector(".invoice-price").value);return {productId:pid,name:name,quantity:q,price:pr,total:q*pr}}).filter(function(i){return i.quantity>0&&i.name})}
function scanInvoiceProduct(){scanBarcode().then(function(code){if(!code)return;var p=active(state.products).find(function(x){return String(x.barcode||"").trim()===String(code).trim()});if(!p){toast("الباركود غير موجود في المنتجات","warning");return}addInvoiceItemRow({productId:p.id,name:p.name,price:p.price,quantity:1});toast("تمت إضافة المنتج","success")})}
function saveInvoice(){var name=val("invCustomerName").trim(),phone=val("invPhone").trim(),date=val("invDate")||today(),paid=toNumber(val("invPaidAmount")),acc=val("invPaidAccount"),items=getInvoiceItems(),total=items.reduce(function(s,i){return s+i.total},0),rem=Math.max(0,total-paid);if(!name||!items.length){toast("أكمل بيانات الفاتورة","warning");return}if(paid>0&&!acc){toast("اختر الحساب الذي دخل عليه المبلغ المدفوع","warning");return}upsertCustomer(name,phone).then(function(c){var inv=nowBase({id:uid("invoice"),customerId:c.id,customerName:name,phone:phone,date:date,items:items,total:total,paid:paid,remaining:rem,accountId:acc,qrValue:""});inv.qrValue="INV|"+inv.id+"|"+name+"|"+total+"|"+paid+"|"+rem;return putOne("invoices",inv).then(function(){return queueSync("invoices",inv.id,"create",inv)}).then(function(){state.lastInvoice=inv;var tasks=[];items.forEach(function(it){if(it.productId)tasks.push(getOne("products",it.productId).then(function(p){if(p){p.quantity=Math.max(0,toNumber(p.quantity)-toNumber(it.quantity));p.updatedAt=Date.now();return putOne("products",p).then(function(){return queueSync("products",p.id,"update",p)})}}))});if(paid>0){var t=nowBase({id:uid("txn"),accountId:acc,type:"income",amount:paid,date:date,note:"دفعة من فاتورة "+name,source:"invoice",sourceId:inv.id});tasks.push(putOne("transactions",t).then(function(){return queueSync("transactions",t.id,"create",t)}));var sale=nowBase({id:uid("sale"),customerId:c.id,name:name,amount:paid,phone:phone,paymentMethod:"account",accountId:acc,source:"invoice",sourceId:inv.id,date:date});tasks.push(putOne("dailySales",sale).then(function(){return queueSync("dailySales",sale.id,"create",sale)}))}if(rem>0){var d=nowBase({id:uid("debt"),customerId:c.id,customerName:name,phone:phone,invoiceId:inv.id,amount:rem,paid:0,remaining:rem,status:"unpaid",date:date,dueDate:"",items:items,source:"invoice"});tasks.push(putOne("debts",d).then(function(){return queueSync("debts",d.id,"create",d)}))}return Promise.all(tasks)})}).then(loadAll).then(function(){clearInvoiceForm();renderCurrent();toast("تم حفظ الفاتورة","success")})}
function clearInvoiceForm(){["invCustomerName","invPhone","invPaidAmount"].forEach(function(id){setVal(id,"")});html("invoiceItems","");setDates();renderAccountOptions();addInvoiceItemRow();calcInvoiceTotal()}
function renderInvoices(){var q=(val("invoiceSearch")||"").toLowerCase();var arr=active(state.invoices).filter(function(i){return !q||(i.customerName+" "+i.phone).toLowerCase().includes(q)}).sort(function(a,b){return b.createdAt-a.createdAt});html("invoiceList",arr.length?tools("invoicesTable","الفواتير")+table(["العميل","الجوال","التاريخ","الإجمالي","المدفوع","المتبقي","الحساب","إجراءات"],arr.map(function(i){return [esc(i.customerName),esc(i.phone||"-"),i.date||"-",money(i.total),money(i.paid),money(i.remaining),esc(accountName(i.accountId)),'<div class="actions"><button class="btn small ghost" data-customer-view="'+i.customerId+'">عرض العميل</button><button class="btn small ghost" data-print-invoice="'+i.id+'">طباعة</button><button class="btn small danger" data-delete="invoices:'+i.id+'">حذف</button></div>']}),"invoicesTable"):'<div class="empty">لا توجد فواتير.</div>');bindCustomerView();document.querySelectorAll("[data-print-invoice]").forEach(function(b){b.onclick=function(){printInvoice(b.dataset.printInvoice)}});bindDelete()}
function printLastInvoice(){var inv=state.lastInvoice||active(state.invoices).sort(function(a,b){return b.createdAt-a.createdAt})[0];if(inv)printInvoice(inv.id);else toast("لا توجد فاتورة","warning")}
function printInvoice(id){var inv=active(state.invoices).find(function(x){return x.id===id});if(!inv)return;var w=window.open("","_blank");w.document.write('<html dir="rtl"><head><title>فاتورة</title><style>body{font-family:Arial;padding:24px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px;text-align:right}.total{font-size:20px;font-weight:bold;margin:10px 0}.barcode{height:50px;width:260px;background:repeating-linear-gradient(90deg,#111 0 2px,transparent 2px 5px,#111 5px 8px,transparent 8px 13px);margin-top:14px}</style></head><body><h1>'+esc(state.settings.storeName)+'</h1><p>العميل: '+esc(inv.customerName)+' - '+esc(inv.phone||"-")+'</p><p>التاريخ: '+esc(inv.date)+'</p><table><thead><tr><th>الصنف</th><th>العدد</th><th>السعر</th><th>المبلغ</th></tr></thead><tbody>'+(inv.items||[]).map(function(i){return '<tr><td>'+esc(i.name)+'</td><td>'+i.quantity+'</td><td>'+money(i.price)+'</td><td>'+money(i.total)+'</td></tr>'}).join("")+'</tbody></table><div class="total">الإجمالي: '+money(inv.total)+'</div><div>المدفوع: '+money(inv.paid)+'</div><div>المتبقي دين: '+money(inv.remaining)+'</div><div class="barcode"></div><p>'+esc(inv.qrValue)+'</p></body></html>');w.document.close();w.print()}

function saveCustomer(){var id=val("customerEditId"),name=val("customerName").trim(),phone=val("customerPhone").trim(),note=val("customerNote").trim();if(!name){toast("اكتب اسم العميل","warning");return}(id?getOne("customers",id):Promise.resolve(null)).then(function(old){var c=nowBase(Object.assign({},old||{},{id:id||uid("customer"),name:name,phone:phone,note:note,createdAt:(old&&old.createdAt)||Date.now()}));return putOne("customers",c).then(function(){return queueSync("customers",c.id,id?"update":"create",c)})}).then(loadAll).then(function(){clearCustomerForm();renderCurrent();toast("تم حفظ العميل","success")})}
function clearCustomerForm(){["customerEditId","customerName","customerPhone","customerNote"].forEach(function(id){setVal(id,"")})}
function editCustomer(id){var c=active(state.customers).find(function(x){return x.id===id});if(!c)return;setVal("customerEditId",c.id);setVal("customerName",c.name||"");setVal("customerPhone",c.phone||"");setVal("customerNote",c.note||"");scrollTo({top:0,behavior:"smooth"})}
function renderCustomers(){var q=(val("customerSearch")||"").toLowerCase();var arr=active(state.customers).filter(function(c){return !q||(c.name+" "+(c.phone||"")).toLowerCase().includes(q)}).sort(function(a,b){return b.createdAt-a.createdAt});html("customersList",arr.length?tools("customersTable","العملاء")+table(["الاسم","الجوال","إجمالي الدين","عدد الفواتير","إجراءات"],arr.map(function(c){var debt=customerDebtTotal(c.id);var invs=active(state.invoices).filter(function(i){return i.customerId===c.id}).length;return [esc(c.name),esc(c.phone||"-"),money(debt),invs,'<div class="actions"><button class="btn small ghost" data-customer-view="'+c.id+'">عرض</button><button class="btn small ghost" data-edit-customer="'+c.id+'">تعديل</button><button class="btn small danger" data-delete="customers:'+c.id+'">حذف</button></div>']}),"customersTable"):'<div class="empty">لا يوجد عملاء.</div>');bindCustomerView();document.querySelectorAll("[data-edit-customer]").forEach(function(b){b.onclick=function(){editCustomer(b.dataset.editCustomer)}});bindDelete()}
function bindCustomerView(){document.querySelectorAll("[data-customer-view]").forEach(function(b){b.onclick=function(){state.selectedCustomerId=b.dataset.customerView;navigate("customers");setTimeout(renderCustomerProfile,0)}})}
function renderCustomerProfile(){var id=state.selectedCustomerId,c=active(state.customers).find(function(x){return x.id===id});if(!c)return;var invs=active(state.invoices).filter(function(i){return i.customerId===id}).sort(function(a,b){return b.createdAt-a.createdAt});var debts=active(state.debts).filter(function(d){return d.customerId===id}).sort(function(a,b){return b.createdAt-a.createdAt});var pays=active(state.payments).filter(function(p){return p.customerId===id}).sort(function(a,b){return b.createdAt-a.createdAt});html("customerProfile",'<div class="card"><div class="customer-head"><div><h3>'+esc(c.name)+'</h3><p class="muted">'+esc(c.phone||"-")+'</p></div><div class="customer-avatar">'+esc((c.name||"?")[0])+'</div></div><div class="grid cards-4" style="margin-top:14px"><div class="card metric" style="box-shadow:none"><b>'+money(debts.reduce(function(s,d){return s+toNumber(d.remaining)},0))+'</b><span>الدين المتبقي</span></div><div class="card metric" style="box-shadow:none"><b>'+invs.length+'</b><span>الفواتير</span></div><div class="card metric" style="box-shadow:none"><b>'+pays.length+'</b><span>الدفعات</span></div></div>'+tools("customerInvoices","فواتير العميل")+table(["التاريخ","الإجمالي","المدفوع","المتبقي"],invs.map(function(i){return [i.date,money(i.total),money(i.paid),money(i.remaining)]}),"customerInvoices")+tools("customerDebts","ديون العميل")+table(["التاريخ","الدين","المدفوع","المتبقي","الحالة"],debts.map(function(d){return [d.date,money(d.amount),money(d.paid),money(d.remaining),chip(debtStatus(d))]}),"customerDebts")+tools("customerPayments","دفعات العميل")+table(["التاريخ","المبلغ","الحساب","ملاحظة"],pays.map(function(p){return [p.date,money(p.amount),esc(accountName(p.accountId)),esc(p.note||"-")]}),"customerPayments")+'</div>')}
function renderManualDebtArea(){if(!$("manualDebtCustomer"))return;var opts=active(state.customers).map(function(c){return '<option value="'+c.id+'">'+esc(c.name)+' - '+esc(c.phone||"")+'</option>'}).join("");html("manualDebtCustomer",opts||'<option value="">أضف عميلًا عبر الفاتورة أولًا</option>')}
function renderDebtsPage(){var q=(val("debtSearch")||"").toLowerCase();var arr=active(state.debts).filter(function(d){return !q||(d.customerName+" "+(d.phone||"")).toLowerCase().includes(q)}).sort(function(a,b){return b.createdAt-a.createdAt});html("debtsList",arr.length?tools("debtsTable","الديون")+table(["العميل","الجوال","التاريخ","أصل الدين","المدفوع","المتبقي","الحالة","إجراءات"],arr.map(function(d){return [esc(d.customerName),esc(d.phone||"-"),d.date||"-",money(d.amount),money(d.paid),money(d.remaining),chip(debtStatus(d)),'<div class="actions"><button class="btn small success" data-pay-debt="'+d.id+'">سداد</button><button class="btn small ghost" data-customer-view="'+d.customerId+'">عرض العميل</button><button class="btn small danger" data-delete="debts:'+d.id+'">حذف</button></div>']}),"debtsTable"):'<div class="empty">لا توجد ديون.</div>');document.querySelectorAll("[data-pay-debt]").forEach(function(b){b.onclick=function(){var s=$("customerPaymentDebt");if(s)s.value=b.dataset.payDebt;var p=$("paymentDebt");if(p)p.value=b.dataset.payDebt}});bindCustomerView();bindDelete()}
function renderCustomerPaymentArea(){if(!$("customerPaymentDebt"))return;renderPaymentDebtOptions()}
function debtStatus(d){if(toNumber(d.remaining)<=0)return"paid";if(toNumber(d.paid)>0)return"partial";return"unpaid"}
function saveManualDebt(){var cid=val("manualDebtCustomer"),amount=toNumber(val("manualDebtAmount")),date=val("manualDebtDate")||today(),note=val("manualDebtNote").trim();var c=active(state.customers).find(function(x){return x.id===cid});if(!c||amount<=0){toast("اختر العميل واكتب المبلغ","warning");return}var d=nowBase({id:uid("debt"),customerId:c.id,customerName:c.name,phone:c.phone,amount:amount,paid:0,remaining:amount,status:"unpaid",date:date,note:note,source:"manual"});putOne("debts",d).then(function(){return queueSync("debts",d.id,"create",d)}).then(loadAll).then(renderCurrent).then(function(){toast("تم إضافة الدين","success")})}
function renderPaymentDebtOptions(){var select=$("paymentDebt")||$("customerPaymentDebt");if(!select)return;var name=val("paymentCustomerName").trim().toLowerCase();var debts=active(state.debts).filter(function(d){return toNumber(d.remaining)>0 && (!name||d.customerName.toLowerCase().includes(name))});select.innerHTML=debts.length?debts.map(function(d){return '<option value="'+d.id+'">'+esc(d.customerName)+' - المتبقي '+money(d.remaining)+'</option>'}).join(""):'<option value="">لا توجد ديون مفتوحة</option>'}
function savePayment(){var debtId=val("paymentDebt")||val("customerPaymentDebt"),amount=toNumber(val("paymentAmount")||val("customerPaymentAmount")),acc=val("paymentAccount"),date=val("paymentDate")||today(),note=val("paymentNote").trim();getOne("debts",debtId).then(function(d){if(!d||amount<=0||!acc){toast("اختر الدين والحساب واكتب المبلغ","warning");throw"stop"}if(amount>toNumber(d.remaining)){toast("المبلغ أكبر من المتبقي","warning");throw"stop"}var rem=toNumber(d.remaining)-amount;var p=nowBase({id:uid("payment"),customerId:d.customerId,customerName:d.customerName,phone:d.phone,debtId:d.id,amount:amount,accountId:acc,date:date,remainingAfterPayment:rem,note:note});return putOne("payments",p).then(function(){return queueSync("payments",p.id,"create",p)}).then(function(){d.paid=toNumber(d.paid)+amount;d.remaining=rem;d.status=rem<=0?"paid":"partial";d.updatedAt=Date.now();return putOne("debts",d).then(function(){return queueSync("debts",d.id,"update",d)})}).then(function(){var t=nowBase({id:uid("txn"),accountId:acc,type:"income",amount:amount,date:date,note:"سداد دين: "+d.customerName,source:"payment",sourceId:p.id});return putOne("transactions",t).then(function(){return queueSync("transactions",t.id,"create",t)})})}).then(loadAll).then(renderCurrent).then(function(){toast("تم تسجيل السداد","success")}).catch(function(){})}
function renderPayments(){var arr=active(state.payments).sort(function(a,b){return b.createdAt-a.createdAt});html("paymentsList",arr.length?tools("paymentsTable","الدفعات")+table(["العميل","التاريخ","المبلغ","الحساب","المتبقي بعد الدفع","ملاحظة"],arr.map(function(p){return [esc(p.customerName),p.date,money(p.amount),esc(accountName(p.accountId)),money(p.remainingAfterPayment),esc(p.note||"-")]}),"paymentsTable"):'<div class="empty">لا توجد دفعات.</div>')}

function renderSales(){var q=(val("salesSearch")||"").toLowerCase(),date=val("salesDateFilter");var arr=active(state.dailySales).filter(function(s){return (!q||(s.name+" "+s.phone).toLowerCase().includes(q))&&(!date||s.date===date)}).sort(function(a,b){return b.createdAt-a.createdAt});text("salesTotal",money(arr.reduce(function(s,x){return s+toNumber(x.amount)},0)));html("salesList",arr.length?tools("salesTable","المبيعات")+table(["الاسم","الجوال","التاريخ","المبلغ","الحساب"],arr.map(function(s){return [esc(s.name),esc(s.phone||"-"),s.date,money(s.amount),esc(accountName(s.accountId))]}),"salesTable"):'<div class="empty">لا توجد مبيعات.</div>')}

function saveProduct(){var id=val("productEditId"),name=val("productName").trim(),price=toNumber(val("productPrice")),barcode=val("productBarcode").trim(),qty=toNumber(val("productQty")),cat=val("productCategory").trim(),min=toNumber(val("productMinQty")||5);if(!name){toast("اكتب اسم المنتج","warning");return}(id?getOne("products",id):Promise.resolve(null)).then(function(old){var p=nowBase(Object.assign({},old||{},{id:id||uid("product"),name:name,price:price,barcode:barcode,quantity:qty,category:cat,minQuantity:min,createdAt:(old&&old.createdAt)||Date.now()}));return putOne("products",p).then(function(){return queueSync("products",p.id,id?"update":"create",p)})}).then(loadAll).then(function(){clearProductForm();renderCurrent();toast("تم حفظ المنتج","success")})}
function clearProductForm(){["productEditId","productName","productPrice","productBarcode","productQty","productCategory","productMinQty"].forEach(function(id){setVal(id,"")})}
function editProduct(id){var p=active(state.products).find(function(x){return x.id===id});if(!p)return;setVal("productEditId",p.id);setVal("productName",p.name);setVal("productPrice",p.price);setVal("productBarcode",p.barcode);setVal("productQty",p.quantity);setVal("productCategory",p.category);setVal("productMinQty",p.minQuantity)}
function renderProducts(){var q=(val("productSearch")||"").toLowerCase();var arr=active(state.products).filter(function(p){return !q||(p.name+" "+p.barcode+" "+p.category).toLowerCase().includes(q)}).sort(function(a,b){return b.createdAt-a.createdAt});html("productsList",arr.length?tools("productsTable","المنتجات")+table(["المنتج","التصنيف","الباركود","السعر","الكمية","إجراءات"],arr.map(function(p){var low=toNumber(p.quantity)<=toNumber(p.minQuantity||0);return [esc(p.name),esc(p.category||"-"),esc(p.barcode||"-"),money(p.price),'<span class="chip '+(low?"danger":"success")+'">'+esc(p.quantity||0)+'</span>','<div class="actions"><button class="btn small ghost" data-edit-product="'+p.id+'">تعديل</button><button class="btn small danger" data-delete="products:'+p.id+'">حذف</button></div>']}),"productsTable"):'<div class="empty">لا توجد منتجات.</div>');document.querySelectorAll("[data-edit-product]").forEach(function(b){b.onclick=function(){editProduct(b.dataset.editProduct)}});bindDelete()}

function renderPurchaseProductOptions(){var s=$("purchaseProduct");if(!s)return;var old=s.value;var arr=active(state.products);s.innerHTML=arr.length?arr.map(function(p){return '<option value="'+p.id+'" '+(old===p.id?"selected":"")+'>'+esc(p.name)+' - كمية '+esc(p.quantity||0)+'</option>'}).join(""):'<option value="">أضف منتجًا أولًا</option>'}
function savePurchase(){var supplier=val("purchaseSupplier").trim(),pid=val("purchaseProduct"),qty=toNumber(val("purchaseQty")),cost=toNumber(val("purchaseUnitCost")),date=val("purchaseDate")||today(),acc=val("purchaseAccount");getOne("products",pid).then(function(p){if(!supplier||!p||qty<=0||!acc){toast("أكمل بيانات الشراء واختر الحساب","warning");throw"stop"}var pur=nowBase({id:uid("purchase"),supplierName:supplier,productId:pid,productName:p.name,quantity:qty,unitCost:cost,totalCost:qty*cost,accountId:acc,date:date});return putOne("purchases",pur).then(function(){return queueSync("purchases",pur.id,"create",pur)}).then(function(){p.quantity=toNumber(p.quantity)+qty;p.updatedAt=Date.now();return putOne("products",p).then(function(){return queueSync("products",p.id,"update",p)})}).then(function(){var t=nowBase({id:uid("txn"),accountId:acc,type:"expense",amount:qty*cost,date:date,note:"شراء من "+supplier,source:"purchase",sourceId:pur.id});return putOne("transactions",t).then(function(){return queueSync("transactions",t.id,"create",t)})})}).then(loadAll).then(function(){["purchaseSupplier","purchaseQty","purchaseUnitCost"].forEach(function(id){setVal(id,"")});renderCurrent();toast("تم حفظ الشراء","success")}).catch(function(){})}
function renderPurchases(){var arr=active(state.purchases).sort(function(a,b){return b.createdAt-a.createdAt});html("purchasesList",arr.length?tools("purchasesTable","المشتريات")+table(["المورد","المنتج","الكمية","التكلفة","الإجمالي","الحساب","التاريخ","إجراءات"],arr.map(function(p){return [esc(p.supplierName),esc(p.productName),p.quantity,money(p.unitCost),money(p.totalCost),esc(accountName(p.accountId)),p.date,'<button class="btn small danger" data-delete="purchases:'+p.id+'">حذف</button>']}),"purchasesTable"):'<div class="empty">لا توجد مشتريات.</div>');bindDelete()}

function hydrateSettings(force){if(state.route!=="settings")return;force=force!==false;var s=state.settings||{};if(force||document.activeElement.id!=="settingStoreName")setVal("settingStoreName",s.storeName||"");if(force||document.activeElement.id!=="settingLogoUrl")setVal("settingLogoUrl",s.logoUrl||"");if(force||document.activeElement.id!=="settingOpeningBalance")setVal("settingOpeningBalance",s.openingBalance||0);if(force||document.activeElement.id!=="settingCurrency")setVal("settingCurrency",s.currency||"شيكل");var img=$("settingsLogoPreview");if(img)img.src=s.logoUrl||""}
function saveSettings(){getOne("settings","main").then(function(cur){cur=cur||{};var s=nowBase(Object.assign({},cur,{id:"main",storeName:val("settingStoreName").trim()||"نظام إدارة المبيعات",logoUrl:val("settingLogoUrl").trim(),openingBalance:toNumber(val("settingOpeningBalance")),currency:val("settingCurrency").trim()||"شيكل",password:val("settingPassword")?val("settingPassword"):cur.password||ACCESS_PASSWORD,createdAt:cur.createdAt||Date.now()}));return putOne("settings",s).then(function(){return queueSync("settings","main","update",s)})}).then(loadAll).then(function(){setVal("settingPassword","");applyBrand();renderCurrent();toast("تم حفظ الإعدادات","success")})}
function renderSyncStatus(){text("pendingCount",(state.syncQueue||[]).filter(function(x){return x.status==="pending"||x.status==="failed"}).length);var last=localStorage.getItem("sales_last_sync");text("lastSyncText",last?new Date(last).toLocaleTimeString("ar"):"-");var logs=(state.syncLogs||[]).sort(function(a,b){return b.createdAt-a.createdAt}).slice(0,20);html("syncLog",logs.length?logs.map(function(x){return '<div class="log-line"><b>'+new Date(x.createdAt).toLocaleString("ar")+'</b><br>'+esc(x.message)+'</div>'}).join(""):'<div class="empty">لا توجد سجلات مزامنة.</div>')}
function exportAllJSON(){var data={};Promise.all(STORES.map(function(s){return getAll(s).then(function(a){data[s]=a})})).then(function(){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="sales-backup-"+today()+".json";a.click();URL.revokeObjectURL(a.href)})}
function clearAllData(){if(!confirm("سيتم حذف البيانات المحلية فقط. هل أنت متأكد؟"))return;Promise.all(STORES.map(clearStore)).then(ensureDefaults).then(loadAll).then(renderCurrent).then(function(){toast("تم حذف البيانات المحلية","success")})}
function softDelete(storeName,id){if(!confirm("تأكيد الحذف؟"))return;getOne(storeName,id).then(function(item){if(!item)return;item.isDeleted=true;item.updatedAt=Date.now();item.syncStatus="pending";return putOne(storeName,item).then(function(){return queueSync(storeName,id,"delete",item)})}).then(loadAll).then(renderCurrent).then(function(){toast("تم الحذف","success")})}
function bindDelete(){document.querySelectorAll("[data-delete]").forEach(function(b){b.onclick=function(){var p=b.dataset.delete.split(":");softDelete(p[0],p[1])}})}

function enhanceSearchSelects(){document.querySelectorAll('select[data-search="1"]').forEach(function(sel){if(sel.dataset.enhanced==="1"){refreshSearchSelect(sel);return}sel.dataset.enhanced="1";sel.classList.add("hidden");var wrap=document.createElement("div");wrap.className="smart-select";var btn=document.createElement("button");btn.type="button";btn.className="smart-select-btn";var menu=document.createElement("div");menu.className="smart-select-menu";var input=document.createElement("input");input.type="search";input.placeholder="بحث...";var list=document.createElement("div");list.className="smart-select-list";menu.appendChild(input);menu.appendChild(list);wrap.appendChild(btn);wrap.appendChild(menu);sel.after(wrap);sel._smart={wrap:wrap,btn:btn,input:input,list:list};btn.onclick=function(){document.querySelectorAll(".smart-select.open").forEach(function(x){if(x!==wrap)x.classList.remove("open")});wrap.classList.toggle("open");input.value="";refreshSearchSelect(sel);setTimeout(function(){input.focus()},20)};input.oninput=function(){refreshSearchSelect(sel)};list.onclick=function(e){var opt=e.target.closest("[data-value]");if(!opt)return;sel.value=opt.dataset.value;sel.dispatchEvent(new Event("change",{bubbles:true}));wrap.classList.remove("open");refreshSearchSelect(sel)};sel.addEventListener("change",function(){refreshSearchSelect(sel)});new MutationObserver(function(){refreshSearchSelect(sel)}).observe(sel,{childList:true,subtree:true,attributes:true});refreshSearchSelect(sel)})}
function refreshSearchSelect(sel){if(!sel._smart)return;var o=sel.options[sel.selectedIndex];sel._smart.btn.innerHTML='<span>'+(o?esc(o.textContent):'اختر')+'</span><span>⌄</span>';var q=(sel._smart.input.value||"").toLowerCase();var opts=[].slice.call(sel.options).filter(function(opt){return opt.textContent.toLowerCase().includes(q)});sel._smart.list.innerHTML=opts.length?opts.map(function(opt){return '<button type="button" data-value="'+esc(opt.value)+'" class="smart-option">'+esc(opt.textContent)+'</button>'}).join(""):'<div class="empty" style="padding:12px">لا توجد نتائج</div>'}
document.addEventListener("click",function(e){if(!e.target.closest(".smart-select")){document.querySelectorAll(".smart-select.open").forEach(function(x){x.classList.remove("open")})}});
function scanBarcode(){return new Promise(function(resolve){var modal=document.createElement("div");modal.className="scanner-modal";modal.innerHTML='<div class="scanner-card"><video id="barcodeVideo" playsinline></video><div class="scanner-actions"><button class="btn primary" id="closeScanner" type="button">إغلاق</button><button class="btn ghost" id="manualBarcode" type="button">إدخال يدوي</button></div></div>';document.body.appendChild(modal);var video=modal.querySelector("video"),controls=null,stream=null,done=false;function close(v){done=true;try{if(controls)controls.stop()}catch(e){}try{if(stream)stream.getTracks().forEach(function(t){t.stop()})}catch(e){}modal.remove();resolve(v||null)}modal.querySelector("#closeScanner").onclick=function(){close(null)};modal.querySelector("#manualBarcode").onclick=function(){close(prompt("أدخل الباركود يدويًا")||null)};if(window.ZXingBrowser&&ZXingBrowser.BrowserMultiFormatReader){var reader=new ZXingBrowser.BrowserMultiFormatReader();reader.decodeFromVideoDevice(null,video,function(result,err,c){controls=c;if(result)close(result.getText())}).catch(function(){toast("تعذر فتح الكاميرا. استخدم HTTPS أو الإدخال اليدوي.","danger")})}else{toast("الكاميرا تحتاج إنترنت لتحميل ماسح الباركود. استخدم الإدخال اليدوي.","warning")}})}

function queueSync(entity,entityId,action,payload){var q={id:uid("queue"),entity:entity,entityId:entityId,action:action,payload:payload,status:"pending",attempts:0,createdAt:Date.now()};return putOne("syncQueue",q).then(function(){showPendingSync();if(navigator.onLine)setTimeout(function(){syncNow(true)},100)})}
function showPendingSync(){setSyncStatus("جاري المزامنة","syncing")}
function setSyncStatus(txt,kind){var cls=kind==="offline"?"offline":kind==="failed"?"failed":kind==="syncing"?"syncing":"";html("syncStatus",'<span class="status-dot '+cls+'"></span><span>'+txt+'</span>');$("syncBtn").classList.toggle("syncing",kind==="syncing")}
function initFirebase(){if(fbReady)return true;if(!window.firebase||!firebase.database)return false;try{if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);fbReady=true;return true}catch(e){return false}}
function path(entity,id){return "systems/"+SYSTEM_KEY+"/"+entity+(id?"/"+id:"")}
function addLog(msg,type){return putOne("syncLogs",{id:uid("log"),message:msg,type:type||"info",createdAt:Date.now()})}
function syncNow(silent){if(syncing)return Promise.resolve();if(!navigator.onLine){setSyncStatus("بدون نت","offline");if(!silent)toast("لا يوجد اتصال","warning");return Promise.resolve()}if(!initFirebase()){setSyncStatus("Firebase غير جاهز","failed");if(!silent)toast("تعذر تحميل Firebase","danger");return Promise.resolve()}syncing=true;setSyncStatus("جاري المزامنة","syncing");return getAll("syncQueue").then(function(qs){qs=qs.filter(function(x){return x.status==="pending"||x.status==="failed"}).sort(function(a,b){return a.createdAt-b.createdAt});var chain=Promise.resolve();qs.forEach(function(item){chain=chain.then(function(){var payload=Object.assign({},item.payload,{updatedAt:Date.now()});if(item.action==="delete")payload.isDeleted=true;return firebase.database().ref(path(item.entity,item.entityId)).set(payload).then(function(){return delOne("syncQueue",item.id)}).then(function(){return getOne(item.entity,item.entityId)}).then(function(local){if(local){local.syncStatus="synced";return putOne(item.entity,local)}}).catch(function(err){item.status="failed";item.attempts=(item.attempts||0)+1;item.error=String(err.message||err);return putOne("syncQueue",item).then(function(){throw err})})})});return chain.then(pullFirebase).then(function(){localStorage.setItem("sales_last_sync",new Date().toISOString());return addLog("تمت المزامنة. العمليات: "+qs.length,"success")})}).then(function(){setSyncStatus("تمت المزامنة","online");if(!silent)toast("تمت المزامنة","success")}).catch(function(err){setSyncStatus("فشل المزامنة","failed");addLog("فشل المزامنة: "+(err.message||err),"danger");if(!silent)toast("فشل المزامنة. راجع Firebase Rules.","danger")}).finally(function(){syncing=false;return loadAll().then(renderCurrent)})}
function pullFirebase(){if(!navigator.onLine||!initFirebase())return Promise.resolve();var ents=STORES.filter(function(s){return !["syncQueue","syncLogs"].includes(s)}),chain=Promise.resolve();ents.forEach(function(entity){chain=chain.then(function(){return firebase.database().ref(path(entity)).once("value").then(function(snap){var vals=Object.values(snap.val()||{}),inner=Promise.resolve();vals.forEach(function(rec){if(!rec||!rec.id)return;inner=inner.then(function(){return getOne(entity,rec.id).then(function(local){if(!local||Number(rec.updatedAt||0)>=Number(local.updatedAt||0)){rec.syncStatus="synced";return putOne(entity,rec)}})})});return inner})})});return chain.then(function(){localStorage.setItem("sales_last_sync",new Date().toISOString())})}
function startRealtime(){if(fbListening||!navigator.onLine||!initFirebase())return;fbListening=true;STORES.filter(function(s){return !["syncQueue","syncLogs"].includes(s)}).forEach(function(entity){firebase.database().ref(path(entity)).on("value",function(snap){var vals=Object.values(snap.val()||{}),chain=Promise.resolve();vals.forEach(function(rec){if(!rec||!rec.id)return;chain=chain.then(function(){return getOne(entity,rec.id).then(function(local){if(!local||Number(rec.updatedAt||0)>=Number(local.updatedAt||0)){rec.syncStatus="synced";return putOne(entity,rec)}})})});chain.then(loadAll).then(renderCurrent)})})}
function watchConnection(){function u(){if(navigator.onLine){setSyncStatus("متصل","online");syncNow(true);startRealtime()}else setSyncStatus("بدون نت","offline")}window.addEventListener("online",u);window.addEventListener("offline",u);u()}
function initPWA(){window.addEventListener("beforeinstallprompt",function(e){e.preventDefault();deferredInstallPrompt=e;$("installBtn").classList.remove("hidden")});$("installBtn").onclick=function(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt=null;$("installBtn").classList.add("hidden")}}}

var templates={
dashboard:function(){return '<div class="section-head"><div><h3>لوحة التحكم</h3><p>ملخص الحسابات والمبيعات والديون.</p></div><button class="btn primary" data-nav="invoices">فاتورة جديدة</button></div><div class="card balance-card"><small>إجمالي أرصدة الحسابات</small><strong id="currentBalance">0</strong><small>يحسب من الرصيد الافتتاحي + الواردات - الصادرات لكل حساب.</small></div><div class="grid cards-6" style="margin-top:14px"><div class="card metric"><div class="metric-icon">'+icon("wallet")+'</div><b id="mTodaySales">0</b><span>مبيعات اليوم</span></div><div class="card metric"><div class="metric-icon">'+icon("receipt")+'</div><b id="mInvoices">0</b><span>عدد الفواتير</span></div><div class="card metric"><div class="metric-icon">'+icon("debt")+'</div><b id="mDebts">0</b><span>ديون مفتوحة</span></div><div class="card metric"><div class="metric-icon">'+icon("account")+'</div><b id="mAccounts">0</b><span>عدد الحسابات</span></div><div class="card metric"><div class="metric-icon">'+icon("users")+'</div><b id="mCustomers">0</b><span>عدد العملاء</span></div><div class="card metric"><div class="metric-icon">'+icon("alert")+'</div><b id="mLowProducts">0</b><span>منتجات ناقصة</span></div></div><div class="card" style="margin-top:14px"><div class="section-head" style="margin-top:0"><div><h3>آخر حركات الحسابات</h3><p>سجل واردات وصادرات مختصر.</p></div></div><div id="recentTransactions"></div></div>'},
invoices:function(){return '<div class="section-head"><div><h3>الفواتير</h3><p>اكتب اسم العميل، المدفوع، والمتبقي يتحول إلى دين تلقائيًا.</p></div><button class="btn ghost" id="clearInvoiceBtn">تفريغ النموذج</button></div><div class="grid two-col"><div class="card"><h3 style="margin-top:0;font-family:Cairo">إنشاء فاتورة</h3><div class="form-grid"><label class="suggest-wrap">اسم العميل<input id="invCustomerName" placeholder="اكتب أول حرفين لظهور اقتراحات"><div id="invCustomerSuggest" class="suggest-box"></div><div id="invCustomerDebtInfo" style="margin-top:8px"></div></label><label>رقم الجوال<input id="invPhone" inputmode="tel"></label><label>التاريخ<input id="invDate" type="date"></label><label>المبلغ المدفوع<input id="invPaidAmount" type="number" min="0" step="0.01" oninput="calcInvoiceTotal()"></label><label class="full">الحساب الذي دخل عليه المدفوع<select id="invPaidAccount" data-search="1"></select></label></div><div class="section-head"><div><h3 style="font-size:18px">الأصناف</h3><p>اختر من المنتجات أو امسح باركود.</p></div><div class="actions"><button class="btn small secondary" id="scanInvoiceBarcodeBtn">مسح باركود</button><button class="btn small primary" id="addInvoiceItemBtn">إضافة صنف</button></div></div><div id="invoiceItems" class="invoice-items"></div><div class="invoice-total"><span>الإجمالي</span><span class="money" id="invoiceTotal">0</span></div><div class="invoice-total"><span>المتبقي كدين</span><span class="money" id="invoiceRemaining">0</span></div><div class="actions" style="margin-top:12px"><button class="btn primary" id="saveInvoiceBtn">حفظ الفاتورة</button><button class="btn ghost" id="printInvoiceBtn">طباعة آخر فاتورة</button></div></div><div class="card"><h3 style="margin-top:0;font-family:Cairo">سجل الفواتير</h3><div class="searchbar"><input id="invoiceSearch" placeholder="بحث"></div><div id="invoiceList"></div></div></div>'},
customers:function(){return '<div class="section-head"><div><h3>العملاء</h3><p>إضافة العملاء ومشاهدة ملف كل عميل.</p></div></div><div id="customerProfile" style="margin-bottom:14px"></div><div class="grid two-col"><div class="card"><h3 style="margin-top:0;font-family:Cairo">إضافة / تعديل عميل</h3><input id="customerEditId" type="hidden"><div class="form-grid"><label>اسم العميل<input id="customerName" placeholder="اسم العميل"></label><label>رقم الجوال<input id="customerPhone" inputmode="tel" placeholder="رقم الجوال"></label><label class="full">ملاحظة<input id="customerNote" placeholder="اختياري"></label></div><div class="actions" style="margin-top:12px"><button class="btn primary" id="saveCustomerBtn">حفظ العميل</button><button class="btn ghost" id="clearCustomerBtn">جديد</button></div></div><div class="card"><h3 style="margin-top:0;font-family:Cairo">قائمة العملاء</h3><div class="searchbar"><input id="customerSearch" placeholder="بحث عن عميل"></div><div id="customersList"></div></div></div>'},
debts:function(){return '<div class="section-head"><div><h3>الديون</h3><p>إضافة دين يدوي وسداد الديون على حساب محدد.</p></div></div><div class="grid two-col"><div class="card"><h3 style="margin-top:0;font-family:Cairo">إضافة دين يدوي</h3><div class="form-grid"><label>العميل<select id="manualDebtCustomer" data-search="1"></select></label><label>المبلغ<input id="manualDebtAmount" type="number" step="0.01"></label><label>التاريخ<input id="manualDebtDate" type="date"></label><label>ملاحظة<input id="manualDebtNote"></label></div><button class="btn primary" style="margin-top:12px" id="saveManualDebtBtn">حفظ الدين</button><hr style="border:0;border-top:1px solid var(--border);margin:16px 0"><h3 style="font-family:Cairo">سداد دفعة</h3><div class="form-grid"><label>الدين<select id="customerPaymentDebt" data-search="1"></select></label><label>الحساب<select id="paymentAccount" data-search="1"></select></label><label>المبلغ<input id="customerPaymentAmount" type="number" step="0.01"></label><label>التاريخ<input id="paymentDate" type="date"></label><label class="full">ملاحظة<input id="paymentNote"></label></div><button class="btn success" style="margin-top:12px" id="saveDebtPaymentBtn">حفظ السداد</button></div><div class="card"><h3 style="margin-top:0;font-family:Cairo">سجل الديون</h3><div class="searchbar"><input id="debtSearch" placeholder="بحث في الديون"></div><div id="debtsList"></div></div></div>'},
accounts:function(){return '<div class="section-head"><div><h3>الحسابات</h3><p>الصندوق، البنك، المحافظ، أو أي جهة مالية.</p></div></div><div class="grid two-col"><div class="card"><h3 style="margin-top:0;font-family:Cairo">إضافة / تعديل حساب</h3><input id="accountEditId" type="hidden"><div class="form-grid"><label>اسم الجهة<input id="accountEntity" placeholder="مثال: البنك / الصندوق"></label><label>اسم الحساب<input id="accountName" placeholder="مثال: حساب رئيسي"></label><label>رصيد افتتاحي<input id="accountOpening" type="number" step="0.01"></label><label>نوع الحساب<select id="accountType" data-search="1"><option value="cash">نقدي</option><option value="bank">بنك</option><option value="wallet">محفظة</option><option value="other">آخر</option></select></label></div><div class="actions" style="margin-top:12px"><button class="btn primary" id="saveAccountBtn">حفظ الحساب</button><button class="btn ghost" id="clearAccountBtn">جديد</button></div><hr style="border:0;border-top:1px solid var(--border);margin:16px 0"><h3 style="font-family:Cairo">وارد / صادر يدوي</h3><div class="form-grid"><label>الحساب<select id="txnAccount" data-search="1"></select></label><label>نوع الحركة<select id="txnType" data-search="1"><option value="income">وارد</option><option value="expense">صادر</option></select></label><label>المبلغ<input id="txnAmount" type="number" step="0.01"></label><label>التاريخ<input id="txnDate" type="date"></label><label class="full">البيان<input id="txnNote"></label></div><button class="btn secondary" style="margin-top:12px" id="saveTxnBtn">حفظ الحركة</button></div><div class="card"><div class="searchbar"><input id="accountSearch" placeholder="بحث في الحسابات"></div><div id="accountsList"></div><div id="transactionsList" style="margin-top:14px"></div></div></div>'},
payments:function(){return '<div class="section-head"><div><h3>سداد الديون</h3><p>اختر الدين والحساب الذي ستدخل عليه الدفعة.</p></div></div><div class="grid two-col"><div class="card"><h3 style="margin-top:0;font-family:Cairo">إضافة دفعة</h3><div class="form-grid"><label class="suggest-wrap">اسم العميل<input id="paymentCustomerName" placeholder="اكتب أول حرفين"><div id="paymentCustomerSuggest" class="suggest-box"></div><div id="paymentCustomerDebtInfo" style="margin-top:8px"></div></label><label>رقم الجوال<input id="paymentPhone"></label><label class="full">الدين<select id="paymentDebt" data-search="1"></select></label><label>المبلغ<input id="paymentAmount" type="number" step="0.01"></label><label>الحساب<select id="paymentAccount" data-search="1"></select></label><label>التاريخ<input id="paymentDate" type="date"></label><label class="full">ملاحظة<input id="paymentNote"></label></div><button class="btn primary" style="margin-top:12px" id="savePaymentBtn">حفظ الدفعة</button></div><div class="card"><h3 style="margin-top:0;font-family:Cairo">سجل الدفعات</h3><div id="paymentsList"></div></div></div>'},
sales:function(){return '<div class="section-head"><div><h3>المبيعات</h3><p>سجل المبالغ المقبوضة من الفواتير.</p></div></div><div class="card"><div class="searchbar"><input id="salesSearch" placeholder="بحث"><input id="salesDateFilter" type="date"></div><div class="invoice-total" style="margin-bottom:12px"><span>الإجمالي</span><span class="money" id="salesTotal">0</span></div><div id="salesList"></div></div>'},
products:function(){return '<div class="section-head"><div><h3>المنتجات</h3><p>إدارة المنتجات والباركود.</p></div></div><div class="grid two-col"><div class="card"><h3 style="margin-top:0;font-family:Cairo">إضافة / تعديل منتج</h3><input id="productEditId" type="hidden"><div class="form-grid"><label>اسم المنتج<input id="productName"></label><label>السعر<input id="productPrice" type="number" step="0.01"></label><label>الباركود<input id="productBarcode"></label><label>الكمية<input id="productQty" type="number"></label><label>التصنيف<input id="productCategory"></label><label>حد التنبيه<input id="productMinQty" type="number"></label></div><div class="actions" style="margin-top:12px"><button class="btn primary" id="saveProductBtn">حفظ</button><button class="btn ghost" id="clearProductBtn">جديد</button><button class="btn secondary" id="scanProductBarcodeBtn">مسح باركود</button></div></div><div class="card"><div class="searchbar"><input id="productSearch" placeholder="بحث"></div><div id="productsList"></div></div></div>'},
purchases:function(){return '<div class="section-head"><div><h3>المشتريات</h3><p>تسجيل شراء يخصم من الحساب ويزيد المخزون.</p></div></div><div class="grid two-col"><div class="card"><h3 style="margin-top:0;font-family:Cairo">إضافة مشتريات</h3><div class="form-grid"><label>المورد<input id="purchaseSupplier"></label><label>المنتج<select id="purchaseProduct" data-search="1"></select></label><label>الكمية<input id="purchaseQty" type="number"></label><label>تكلفة الوحدة<input id="purchaseUnitCost" type="number" step="0.01"></label><label>الحساب المدفوع منه<select id="purchaseAccount" data-search="1"></select></label><label>التاريخ<input id="purchaseDate" type="date"></label></div><button class="btn primary" style="margin-top:12px" id="savePurchaseBtn">حفظ الشراء</button></div><div class="card"><div id="purchasesList"></div></div></div>'},
settings:function(){return '<div class="section-head"><div><h3>الإعدادات</h3><p>تغيير الاسم والصورة وكلمة المرور والمزامنة.</p></div></div><div class="grid two-col"><div class="card"><h3 style="margin-top:0;font-family:Cairo">إعدادات عامة</h3><div class="form-grid"><label>اسم النظام<input id="settingStoreName"></label><label>رابط الصورة<input id="settingLogoUrl"></label><label>رصيد بداية عام<input id="settingOpeningBalance" type="number" step="0.01"></label><label>العملة<input id="settingCurrency"></label><label>كلمة مرور جديدة<input id="settingPassword" type="password" placeholder="اتركها فارغة إن لم ترد تغييرها"></label><label>معاينة<img id="settingsLogoPreview" class="settings-logo-preview"></label></div><div class="actions" style="margin-top:12px"><button class="btn primary" id="saveSettingsBtn">حفظ</button><button class="btn ghost" id="exportDataBtn">نسخة JSON</button><button class="btn danger" id="clearDataBtn">حذف المحلي</button></div></div><div class="card"><h3 style="margin-top:0;font-family:Cairo">المزامنة والتثبيت</h3><div class="grid cards-4"><div class="card metric" style="box-shadow:none"><div class="metric-icon">'+icon("clock")+'</div><b id="pendingCount">0</b><span>عمليات معلقة</span></div><div class="card metric" style="box-shadow:none"><div class="metric-icon">'+icon("cloud")+'</div><b id="lastSyncText">-</b><span>آخر مزامنة</span></div></div><div class="actions" style="margin-top:12px"><button class="btn primary" id="settingsSyncBtn">مزامنة الآن</button><button class="btn ghost" id="pullBtn">سحب Firebase</button></div><div id="syncLog" class="sync-log" style="margin-top:12px"></div></div></div>'}
};

})();
